### PR TITLE
The input is no longer blocking

### PR DESCRIPTION
**Pull request by wgaffa**
* Added input handling on a seperate thread
* Sends the termion::Event::Key through a channel
* A tokio task loops until it receives a key event

Additional stuff
* Removed an old match statement no longer needed which
  in turn needed alot of reformatting as well.
* Alot of the changed lines are just some indenting removed.

### CODE REVIEW

**Comment by wgaffa** [comment]
Before accepting read how to test before merging PR's

https://stackoverflow.com/questions/27567846/how-can-i-check-out-a-github-pull-request-with-git

**Comment by wgaffa** [comment]
Oh yes, there are some unimplemented! macro calls there that you can handle better or we can just panic.
If you want a specific way to handle error messages we can discuss it later.

**Review by brandontdev — APPROVED** [review]
All of this looks good. I'll look over the error-handling mentioned, I think we should handle the key errors with something on the user's end.

**Comment by brandontdev** [comment]
Merged.

**Pull request merged**
